# DeepPresenter 配置文件
research_agent:
  base_url: "base_url_here"
  model: "anthropic/claude-sonnet-4.5"
  api_key: "your_key"

design_agent:
  base_url: "base_url_here"
  model: "google/gemini-2.5-pro"
  api_key: "your_key"

long_context_model:
  base_url: "base_url_here"
  model: "glm-4.6"
  api_key: "your_key"

vision_model:
  base_url: "base_url_here"
  model: "vision_model"
  api_key: "your_key"

t2i_model:
  base_url: "base_url_here"
  model: "t2i_model"
  api_key: "your_key"
  sampling_parameters:
    response_format: "b64_json"
    extra_body: { "watermark": False }
